import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Navbar } from "./components/Navbar/Navbar";
import "./globals.css";
import  StoreProvider from "./storeProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

//Un layout è un componente UI condiviso tra diverse pagine o sezioni di un'applicazione. 
// Viene utilizzato per definire la struttura comune dell'applicazione, come l'intestazione, il piè di pagina o la barra di navigazione. 
// In questo caso, il layout include il componente Navbar e avvolge tutti i componenti figli con il StoreProvider, 
// rendendo il Redux store disponibile in tutta l'applicazione.
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <StoreProvider>
          <Navbar />
          {children}
        </StoreProvider>
      </body>
    </html>
  );
}
